### PR TITLE
feature/63

### PR DESCRIPTION
**Pull request by zolkol0077**
@fovecsernyes please check if it looks like something that you imagined.
If yes I will clean up the code and fix the minor bugs.

### CODE REVIEW

**Comment by fovecsernyes** [comment]
yes, something like this. but there should be 2 seperate functions:
- a night mode
- a mode with bigger fonts, but with same light colors

**Review by fovecsernyes — CHANGES_REQUESTED** [review]
yes, something like this. but there should be 2 seperate functions:

a night mode
a mode with bigger fonts, but with same light colors

**Comment by zolkol0077** [comment]
> yes, something like this. but there should be 2 seperate functions:
> 
> a night mode
> a mode with bigger fonts, but with same light colors

The second request makes no sense.
If they want bigger fonts with the same colour scheme then they can zoom in manually.
I believe the original request was high contrast, easy to read mode for people with vision problems.
The night mode would require styling which our original theme is also lacking of.

**Comment by fovecsernyes** [comment]
@zolkol0077 good point, you can leave it that way, but please position it better (placing next to the flag does not look good), and find a better icon.

**Comment by fovecsernyes** [comment]
@zolkol0077 are you planning to continue working on this task?

**Comment by zolkol0077** [comment]
yes, I will finish this before the weekend

**Comment by zolkol0077** [comment]
Fixed the position of the button so it's not bugging with the flag.
Tried to swap the icon for something nicer but none of them looked good on that yellow header so I kept this one.

Tried to make some backend support for the view so the settings do not reset when changing page but I had no energy to study any backend stuff to implement it.

**Review by fovecsernyes — CHANGES_REQUESTED** [review]
Please take your time, or seek for help our facebook group. i will not merge it until the theme changing changes back after chaning a page.

**Comment by fovecsernyes** [comment]
@zolkol0077 will you do this?

> Please take your time, or seek for help our facebook group. i will not merge it until the theme changing changes back after chaning a page.

Will you do this?

**Comment by zolkol0077** [comment]
I will try to solve this, probably without backend stuff.

**Comment by zolkol0077** [comment]
> i will not merge it until the theme changing changes back after chaning a page.

issue fixed

**Review by fovecsernyes — APPROVED** [review]
looks OK, thanks

**Pull request merged**
