### PR TITLE
Feature/54

### PR DESCRIPTION
**Pull request by Leriel9**
I created the backand for 'My orders'. I needed to change the db structure for this: Order got associated with Address in a one-to-one relationship.

### CODE REVIEW

**Review by fovecsernyes — CHANGES_REQUESTED** [review]
Please fix db issues.

**Comment by Leriel9** [comment]
> 
> 
> Please fix db issues.

Check out the latest commit. You might have to rebuild docker images for it to work.

**Review by fovecsernyes — CHANGES_REQUESTED** [review]
before making migrations i got the following error:
```
app_1       | CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0002_auto_20191105_1534, 0005_order_o_t_o_address_order in app).
app_1       | To fix them run 'python manage.py makemigrations --merge'
app_1       | CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0005_order_o_t_o_address_order, 0002_auto_20191105_1534 in app).
app_1       | To fix them run 'python manage.py makemigrations --merge'
app_1       | Retry!
app_1       | CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0005_order_o_t_o_address_order, 0002_auto_20191105_1534 in app).
app_1       | To fix them run 'python manage.py makemigrations --merge'
app_1       | Retry!
app_1       | CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0002_auto_20191105_1534, 0005_order_o_t_o_address_order in app).
app_1       | To fix them run 'python manage.py makemigrations --merge'
```

the i ran 'python manage.py makemigrations --merge' inside the container and the following error occured:

```
pp_1       | Operations to perform:
app_1       |   Apply all migrations: admin, app, auth, contenttypes, sessions
app_1       | Running migrations:
app_1       |   Applying app.0002_auto_20191105_1534...Traceback (most recent call last):
app_1       |   File "manage.py", line 15, in <module>
app_1       |     execute_from_command_line(sys.argv)
app_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
app_1       |     utility.execute()
app_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
app_1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
app_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
app_1       |     self.execute(*args, **cmd_options)
app_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
app_1       |     output = self.handle(*args, **options)
app_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
app_1       |     res = handle_func(*args, **kwargs)
app_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
app_1       |     post_migrate_state = executor.migrate(
app_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
app_1       |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
app_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
app_1       |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
app_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
app_1       |     state = migration.apply(state, schema_editor)
app_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 114, in apply
app_1       |     operation.state_forwards(self.app_label, project_state)
app_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 172, in state_forwards
app_1       |     delay = not old_field.is_relation
app_1       | AttributeError: 'NoneType' object has no attribute 'is_relation'
app_1       | Retry!
```

the app has been rebuilt

**Comment by fovecsernyes** [comment]
> before making migrations i got the following error:
> 
> ```
> app_1       | CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0002_auto_20191105_1534, 0005_order_o_t_o_address_order in app).
> app_1       | To fix them run 'python manage.py makemigrations --merge'
> app_1       | CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0005_order_o_t_o_address_order, 0002_auto_20191105_1534 in app).
> app_1       | To fix them run 'python manage.py makemigrations --merge'
> app_1       | Retry!
> app_1       | CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0005_order_o_t_o_address_order, 0002_auto_20191105_1534 in app).
> app_1       | To fix them run 'python manage.py makemigrations --merge'
> app_1       | Retry!
> app_1       | CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0002_auto_20191105_1534, 0005_order_o_t_o_address_order in app).
> app_1       | To fix them run 'python manage.py makemigrations --merge'
> ```
> 
> the i ran 'python manage.py makemigrations --merge' inside the container and the following error occured:
> 
> ```
> pp_1       | Operations to perform:
> app_1       |   Apply all migrations: admin, app, auth, contenttypes, sessions
> app_1       | Running migrations:
> app_1       |   Applying app.0002_auto_20191105_1534...Traceback (most recent call last):
> app_1       |   File "manage.py", line 15, in <module>
> app_1       |     execute_from_command_line(sys.argv)
> app_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
> app_1       |     utility.execute()
> app_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
> app_1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
> app_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
> app_1       |     self.execute(*args, **cmd_options)
> app_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
> app_1       |     output = self.handle(*args, **options)
> app_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
> app_1       |     res = handle_func(*args, **kwargs)
> app_1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
> app_1       |     post_migrate_state = executor.migrate(
> app_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
> app_1       |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
> app_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
> app_1       |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
> app_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
> app_1       |     state = migration.apply(state, schema_editor)
> app_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/migration.py", line 114, in apply
> app_1       |     operation.state_forwards(self.app_label, project_state)
> app_1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/operations/fields.py", line 172, in state_forwards
> app_1       |     delay = not old_field.is_relation
> app_1       | AttributeError: 'NoneType' object has no attribute 'is_relation'
> app_1       | Retry!
> ```
> 
> the app has been rebuilt

i have cleaned up everything and now it is working.

**Review by fovecsernyes — APPROVED** [review]
cool

**Pull request merged**
