### PR TITLE
Feature/68

### PR DESCRIPTION
**Pull request by leaderhun**
General design with blue dominant colors.
Darker mode available by adding "darker" class to body.

### CODE REVIEW

**Review by fovecsernyes — CHANGES_REQUESTED** [review]
Go to admin -> add a "Pizzas" (catgory is required)-> check the Pizzas page on the frontend -> you can not read the decription, because it is white and gray.

**Comment by leaderhun** [comment]
> Go to admin -> add a "Pizzas" (catgory is required)-> check the Pizzas page on the frontend -> you can not read the decription, because it is white and gray.

done

**Comment by fovecsernyes** [comment]
Please resolve merging conflicts, because i am not sure at src/app/templates/pizzalist.html.

**Review by fovecsernyes — APPROVED** [review]
looks cool.

**Comment by fovecsernyes** [comment]
http://localhost:8000/en/shoppingcart has no style. please fix this and i'll merge it. thanks

**Pull request merged**
