### PR TITLE
Feature/6

### PR DESCRIPTION
**Pull request by leaderhun**

### CODE REVIEW

**Review by fovecsernyes — CHANGES_REQUESTED** [review]
I noticed some problems:

- i can not save my custom made pizza
- i can not set exceptions for allergens on pizza page
- reviews are not neccessary on the home page, but recommendations are missing

**Comment by fovecsernyes** [comment]
@leaderhun customized pizza saving is still missing. could you please correct it?

**Comment by leaderhun** [comment]
> @leaderhun customized pizza saving is still missing. could you please correct it?

ofc, when i get home from work. That's gonna be after 6pm every day in the future :)

**Review by fovecsernyes — APPROVED** [review]
good job

**Pull request merged**
