### PR TITLE
Feature/69

### PR DESCRIPTION
**Pull request by 96dervalics**

### CODE REVIEW

**Comment by Leriel9** [comment]
You can test the cart function on 'Pizzas' (if you create a FoodProduct).

Unfortunately the 'Pizzas' page implements the Pizza class from the old models.py file. (That file is completely unnecessary.) We can't use that class, because it doesn't have an ID field; we used FoodProduct, so we couldn't really connect the orders with the cart. Right now where are adding the first FoodProduct (id = 1) to the cart, disregarding the actual choice.

**Comment by fovecsernyes** [comment]
> You can test the cart function on 'Pizzas' (if you create a FoodProduct).
> 
> Unfortunately the 'Pizzas' page implements the Pizza class from the old models.py file. (That file is completely unnecessary.) We can't use that class, because it doesn't have an ID field; we used FoodProduct, so we couldn't really connect the orders with the cart. Right now where are adding the first FoodProduct (id = 1) to the cart, disregarding the actual choice.

@martonur can you have a look on this?

**Review by fovecsernyes — CHANGES_REQUESTED** [review]
Please try to add an id to the pizza class which can be accessed at http://localhost:8000/en/admin/app/pizza/add/ .

**Comment by Leriel9** [comment]
> Please try to add an id to the pizza class which can be accessed at http://localhost:8000/en/admin/app/pizza/add/ .

@fovecsernyes We changed to the pizza class. It's working now.

**Comment by fovecsernyes** [comment]
looks great, please resolve the conflicts (carefully) and i will merge it.

**Review by fovecsernyes — APPROVED** [review]

**Comment by fovecsernyes** [comment]
Can I ask you to merge the master into your branch. I do not want to break anything.

**Pull request merged**
