### PR TITLE
Feature/11

### PR DESCRIPTION
**Pull request by vattila96**
Added css to user authentication pages.

### CODE REVIEW

**Review by fovecsernyes — CHANGES_REQUESTED** [review]
Generally, centering the content is not a great idea, since jumping from Sign up to Login is strange.

**Sign up page:**
1. Sign up button has a line break which is not neccessary and does not look good.
2. it is not responsive. The input fields should be fixed in size (they get small when resizing) and the _Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only._ and the _Enter the same password as before, for verification._ texts should have a line break before.

**Login page:**
1. Also not responsive, the input fields can get too small (like the buttons).

**Reset page**
1. The text on the button needs more padding.
2. the input field is not round like in Login and signup pages.

**Comment by fovecsernyes** [comment]
@vattila96 please tell me when it is up for a review again.

**Comment by vattila96** [comment]
@fovecsernyes  I updated it, please review it.

**Review by fovecsernyes — CHANGES_REQUESTED** [review]
Please add some margin to the left side of the pages. If this is done, I'll merge it. Thanks

**Comment by vattila96** [comment]
@fovecsernyes I updated it

**Review by fovecsernyes — APPROVED** [review]
Perfect, thanks

**Pull request merged**
