### PR TITLE
Feature/26

### PR DESCRIPTION
**Pull request by atesztoth**
- added .editorconfig so finally formatting will be common
- fixed requirements.txt
- updated readme
- added models to admin
- fixed issues arising from NOT using snake_case
- fixed wrong imports
- minor changes

### CODE REVIEW

**Review by fovecsernyes — CHANGES_REQUESTED** [review]
There is a problem with the entities, for repro do the following:

1. Go to Admin
2. login (admin:password)
3. click on one of the entities
4. you'll get the following error message:

```
Request Method: | GET
-- | --
http://localhost:8000/hu/admin/app/courier/
2.2.6
ProgrammingError
relation "app_courier" does not exist LINE 1: SELECT COUNT(*) AS "__count" FROM "app_courier"                                           ^
/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py in _execute, line 84
/usr/local/bin/python
3.7.4
['/usr/src/app/src',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages']
csüt, 24 Okt 2019 10:57:54 +0000
```

**Comment by atesztoth** [comment]
> There is a problem with the entities, for repro do the following:
> 
> 1. Go to Admin
> 2. login (admin:password)
> 3. click on one of the entities
> 4. you'll get the following error message:
> 
> ```
> Request Method: | GET
> -- | --
> http://localhost:8000/hu/admin/app/courier/
> 2.2.6
> ProgrammingError
> relation "app_courier" does not exist LINE 1: SELECT COUNT(*) AS "__count" FROM "app_courier"                                           ^
> /usr/local/lib/python3.7/site-packages/django/db/backends/utils.py in _execute, line 84
> /usr/local/bin/python
> 3.7.4
> ['/usr/src/app/src',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages']
> csüt, 24 Okt 2019 10:57:54 +0000
> ```

This is not true. The problem is that you have an outdated version of the db. type `docker volume ls` find the name of container:pg (something like this). Then `docker volume rm <insert name here>`. After that you can rebuild and rerun the app. This is a not a problem with this PR, only the migration engine sees that tables exists in your version.

**Comment by atesztoth** [comment]
Btw this problem arises because the migrations was not committed with the rest of the code yet. Everyone should add and commit their migrations, which should be consistent.

**Comment by atesztoth** [comment]
> There is a problem with the entities, for repro do the following:
> 
> 1. Go to Admin
> 2. login (admin:password)
> 3. click on one of the entities
> 4. you'll get the following error message:
> 
> ```
> Request Method: | GET
> -- | --
> http://localhost:8000/hu/admin/app/courier/
> 2.2.6
> ProgrammingError
> relation "app_courier" does not exist LINE 1: SELECT COUNT(*) AS "__count" FROM "app_courier"                                           ^
> /usr/local/lib/python3.7/site-packages/django/db/backends/utils.py in _execute, line 84
> /usr/local/bin/python
> 3.7.4
> ['/usr/src/app/src',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/site-packages']
> csüt, 24 Okt 2019 10:57:54 +0000
> ```

OK it was true but it felt good writing it is not 😂😂

**Comment by fovecsernyes** [comment]
The docker-compose down command was missing when shutting down the app, so this basically solves the issue.

**Review by fovecsernyes — COMMENTED** [review]
thanks for it, looks OK

**Pull request merged**
