### PR TITLE
Feature/52

### LINKED ISSUE #52: #feature - Payment
Please investigate and implement a DEMO paying site (for example OTP simplepay). It should be as simple as possible. 

Some useful sites:
- https://portal-sandbox.openbanking.otpbank.hu/#/
- https://www.simplepay.hu/fejlesztoknek

### PR DESCRIPTION
**Pull request by atesztoth**
- added new separate server for payment simulation (and/or every other 3rd pt service simulation is possible)
- docker-compose up will run the server on port 9000

fixes #52

### CODE REVIEW

**Review by fovecsernyes — CHANGES_REQUESTED** [review]
I have the following error msg:

```container_payment-server_1 exited with code 1
payment-server_1  | internal/modules/cjs/loader.js:895
payment-server_1  |     throw err;
payment-server_1  |     ^
payment-server_1  |
payment-server_1  | Error: Cannot find module '/usr/src/app/dist/server.js'
payment-server_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
payment-server_1  |     at Function.Module._load (internal/modules/cjs/loader.js:785:27)
payment-server_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12)
payment-server_1  |     at internal/main/run_main_module.js:16:11 {
payment-server_1  |   code: 'MODULE_NOT_FOUND',
payment-server_1  |   requireStack: []
payment-server_1  | }
container_payment-server_1 exited with code 1```

**Comment by atesztoth** [comment]
yep seems like dist folder isnt copied. hope it is not my f*king git again, because lately it it fails to add files to my commits...

**Comment by atesztoth** [comment]
will look into it tonight

**Comment by atesztoth** [comment]
@fovecsernyes Fixed issues!
Extras:
- cold start script that rebuilds the containers before running them
- src folder of payment server is linked into the container so every change made there will be reflected after a restart

Suggested development procedure for payment server:
- installing node locally
- run yarn dev
- modify sources * do the magic *
- test changes via starting the app

**Review by fovecsernyes — APPROVED** [review]
:beers:

**Pull request merged**
